.TH cvsup-ports.sh 1 "July 20, 2007"
.SH NAME
cvsup-ports.sh
.SH SYNOPSIS
.B cvsup-ports.sh
.SH DESCRIPTION
.B cvsup-ports.sh
is a simple script that updates a FreeBSD system's ports collection. The script downloads Ports changes, updates the index files, updates the portaudit database if necessary, and downloads the appropriate distribution files.
.SH AUTHOR(S)
.B Alexis Megas
