.TH find-broken-links.sh 1 "February 28, 2025"
.SH NAME
find-broken-links.sh
.SH SYNOPSIS
.B find-broken-links.sh [options]
.SH DESCRIPTION
.B find-broken-links.sh
locates broken symbolic links.
.SH OPTIONS
.TP
.BI -d " DIR"
Specify which directory to act on.
.TP
.BI -r
If specified, the broken link is removed.
.SH AUTHOR(S)
.B Alexis Megas
