.TH find_core_files.sh 1 "March 18, 2007"
.SH NAME
find_core_files.sh
.SH SYNOPSIS
.B find_core_files.sh
.SH DESCRIPTION
.B find_core_files.sh
is a simple script that runs the find and file commands in the root (/) directory against all regular files. If the file command returns the string core file, the respective file's name is written to a temporary file in /tmp (/tmp/corefiles).
.SH AUTHOR(S)
.B Alexis Megas
