.TH find_consecutive_empty_lines.bash 1 "August 24, 2019"
.SH NAME
find_consecutive_empty_lines.bash
.SH SYNOPSIS
.B find_consecutive_empty_lines.bash
.SH DESCRIPTION
.B find_consecutive_empty_lines.bash
may be used to discover consecutive empty lines in provided file(s).
.SH AUTHOR(S)
.B Alexis Megas
