.TH nsplit.sh 1 "March 18, 2007"
.SH NAME
nsplit.sh
.SH SYNOPSIS
.B nsplit.sh [options]
.SH DESCRIPTION
.B nsplit.sh
is a simple script that splits a file into at least n parts. It uses split -b to separate the file.
.SH OPTIONS
.IP "-f FILE"
Specify the file to act on.
.IP "-n N (>1)"
Specify the number of parts to split the file into.
.SH AUTHOR(S)
.B Alexis Megas
