.TH nsplit.sh 1 "February 28, 2025"
.SH NAME
nsplit.sh
.SH SYNOPSIS
.B nsplit.sh [options]
.SH DESCRIPTION
.B nsplit.sh
splits a file into at least n parts.
.SH OPTIONS
.TP
.BI -f " FILE"
Specify the file to act on.
.TP
.BI -n " N"
Specify the number of parts to split the file into.
.SH AUTHOR(S)
.B Alexis Megas
