.TH postgresql_backup.sh 1 "June 26, 2014"
.SH NAME
postgresql_backup.sh
.SH SYNOPSIS
.B postgresql_backup.sh [options]
.SH DESCRIPTION
.B postgresql_backup.sh
is a simple script that performs a PostgreSQL backup via the pg_dumpall utility. The script uses the options --clean, --file=pg_dumpall.$$, --host=localhost, and --password.
.SH OPTIONS
Please see the pg_dumpall manual.
.SH AUTHOR(S)
.B Alexis Megas
