.TH recycle-swap.sh 1 "February 28, 2025"
.SH NAME
recycle-swap.sh
.SH SYNOPSIS
.B recycle-swap.sh [options]
.SH DESCRIPTION
.B recycle-swap.sh
recycles swap. It does so by deactivating
swap if the available physical memory is sufficiently large.
Swap will be reactivated before the script terminates.
.SH OPTIONS
.TP
.BI -p " percent"
Specify a safety percent. If p >= 100 * (Free Physical Memory -
Consumed Swap) / Total Physical Memory, then the swap area will be
recycled. If the free physical memory is less than or equal to the
consumed swap, the program will not recycle swap. A default of 25
percent is considered.
.SH AUTHOR(S)
.B Alexis Megas
