.TH stop-user-processes.sh 1 "February 28, 2025"
.SH NAME
stop-user-processes.sh
.SH SYNOPSIS
.B stop-user-processes.sh [options]
.SH DESCRIPTION
.B stop-user-processes.sh
allows the superuser to CONTINUE or STOP a user's
processes. The script supports both interactive and non-interactive modes.
.SH OPTIONS
.TP
.BI -c
Send a CONTINUE signal.
.TP
.BI -f
Force the action to occur.
.TP
.BI -s
Send a STOP signal.
.TP
.BI -u " userid"
Specify the userid to act on.
.SH AUTHOR(S)
.B Alexis Megas
